# netlify.toml
# This file tells Netlify how to handle routes for a single-page application

[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Clean install and build command to fix Rollup dependency issues
  command = "rm -rf node_modules && npm install --force && npm run build"
  
[build.environment]
  # Use Node.js 18 for better compatibility
  NODE_VERSION = "18"
  # Ensure npm uses latest version
  NPM_FLAGS = "--legacy-peer-deps"

# The following redirect is intended for use with single-page applications (SPA)
# where the app handles routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200