import { FrontendMaintenanceTransaction } from "@/integration/supabase/types/maintenance-transaction";

export const mockMaintenanceTransactions: FrontendMaintenanceTransaction[] = [
  {
    id: "1",
    vehicleId: "1",
    maintenanceTypeId: "1",
    date: "2024-01-15",
    issue: "Regular maintenance",
    amount: 55.99,
    notes: "Changed oil and filter, topped off fluids",
    performedBy: "Quick Lube Service",
    status: "Completed",
    receiptUrl: null,
    vehicleInfo: "2020 Toyota Camry (ABC123)",
    maintenanceTypeName: "Oil Change"
  },
  {
    id: "2",
    vehicleId: "2",
    maintenanceTypeId: "3",
    date: "2024-02-10",
    issue: "Squeaking when braking",
    amount: 325.50,
    notes: "Replaced front brake pads and rotors",
    performedBy: "City Auto Repair",
    status: "Completed",
    receiptUrl: null,
    vehicleInfo: "2021 Honda Civic (XYZ789)",
    maintenanceTypeName: "Brake Replacement"
  },
  {
    id: "3",
    vehicleId: "3",
    maintenanceTypeId: "2",
    date: "2024-01-25",
    issue: "Routine maintenance",
    amount: 35.00,
    notes: "Rotated tires and checked pressure",
    performedBy: "Discount Tire",
    status: "Completed",
    receiptUrl: null,
    vehicleInfo: "2019 Ford F-150 (DEF456)",
    maintenanceTypeName: "Tire Rotation"
  },
  {
    id: "4",
    vehicleId: "4",
    maintenanceTypeId: "4",
    date: "2024-03-05",
    issue: "Annual inspection due",
    amount: 95.00,
    notes: "Passed inspection with no issues",
    performedBy: "State Inspection Center",
    status: "Completed",
    receiptUrl: null,
    vehicleInfo: "2022 Chevrolet Silverado (GHI789)",
    maintenanceTypeName: "Annual Inspection"
  },
  {
    id: "5",
    vehicleId: "5",
    maintenanceTypeId: "7",
    date: "2024-03-15",
    issue: "A/C not cooling properly",
    amount: 375.25,
    notes: "Recharged refrigerant and replaced compressor",
    performedBy: "Tesla Service Center",
    status: "Completed",
    receiptUrl: null,
    vehicleInfo: "2021 Tesla Model 3 (JKL012)",
    maintenanceTypeName: "Air Conditioning Repair"
  },
  {
    id: "6",
    vehicleId: "1",
    maintenanceTypeId: "6",
    date: "2024-04-20",
    issue: "Transmission service due",
    amount: 210.00,
    notes: "Changed transmission fluid and filter",
    performedBy: "Toyota Dealership",
    status: "Scheduled",
    receiptUrl: null,
    vehicleInfo: "2020 Toyota Camry (ABC123)",
    maintenanceTypeName: "Transmission Service"
  },
  {
    id: "7",
    vehicleId: "3",
    maintenanceTypeId: "8",
    date: "2024-02-15",
    issue: "Vehicle broke down on highway",
    amount: 175.00,
    notes: "Towed to service center, jump started battery",
    performedBy: "AAA Roadside Assistance",
    status: "Completed",
    receiptUrl: null,
    vehicleInfo: "2019 Ford F-150 (DEF456)",
    maintenanceTypeName: "Emergency Roadside Assistance"
  }
];
