-- Create Countries Table and Populate with World Countries
-- Migration: 20251002_create_countries_table.sql

-- Create countries table
CREATE TABLE IF NOT EXISTS countries (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    code TEXT NOT NULL UNIQUE, -- ISO 3166-1 alpha-2 country code
    region TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for better performance
CREATE INDEX IF NOT EXISTS idx_countries_name ON countries(name);
CREATE INDEX IF NOT EXISTS idx_countries_code ON countries(code);

-- Insert all world countries
INSERT INTO countries (name, code, region) VALUES
-- Africa
('Algeria', 'DZ', 'Africa'),
('Angola', 'AO', 'Africa'),
('Benin', 'BJ', 'Africa'),
('Botswana', 'BW', 'Africa'),
('Burkina Faso', 'BF', 'Africa'),
('Burundi', 'BI', 'Africa'),
('Cameroon', 'CM', 'Africa'),
('Cape Verde', 'CV', 'Africa'),
('Central African Republic', 'CF', 'Africa'),
('Chad', 'TD', 'Africa'),
('Comoros', 'KM', 'Africa'),
('Congo', 'CG', 'Africa'),
('Democratic Republic of the Congo', 'CD', 'Africa'),
('Djibouti', 'DJ', 'Africa'),
('Egypt', 'EG', 'Africa'),
('Equatorial Guinea', 'GQ', 'Africa'),
('Eritrea', 'ER', 'Africa'),
('Eswatini', 'SZ', 'Africa'),
('Ethiopia', 'ET', 'Africa'),
('Gabon', 'GA', 'Africa'),
('Gambia', 'GM', 'Africa'),
('Ghana', 'GH', 'Africa'),
('Guinea', 'GN', 'Africa'),
('Guinea-Bissau', 'GW', 'Africa'),
('Ivory Coast', 'CI', 'Africa'),
('Kenya', 'KE', 'Africa'),
('Lesotho', 'LS', 'Africa'),
('Liberia', 'LR', 'Africa'),
('Libya', 'LY', 'Africa'),
('Madagascar', 'MG', 'Africa'),
('Malawi', 'MW', 'Africa'),
('Mali', 'ML', 'Africa'),
('Mauritania', 'MR', 'Africa'),
('Mauritius', 'MU', 'Africa'),
('Morocco', 'MA', 'Africa'),
('Mozambique', 'MZ', 'Africa'),
('Namibia', 'NA', 'Africa'),
('Niger', 'NE', 'Africa'),
('Nigeria', 'NG', 'Africa'),
('Rwanda', 'RW', 'Africa'),
('Sao Tome and Principe', 'ST', 'Africa'),
('Senegal', 'SN', 'Africa'),
('Seychelles', 'SC', 'Africa'),
('Sierra Leone', 'SL', 'Africa'),
('Somalia', 'SO', 'Africa'),
('South Africa', 'ZA', 'Africa'),
('South Sudan', 'SS', 'Africa'),
('Sudan', 'SD', 'Africa'),
('Tanzania', 'TZ', 'Africa'),
('Togo', 'TG', 'Africa'),
('Tunisia', 'TN', 'Africa'),
('Uganda', 'UG', 'Africa'),
('Zambia', 'ZM', 'Africa'),
('Zimbabwe', 'ZW', 'Africa'),

-- Asia
('Afghanistan', 'AF', 'Asia'),
('Armenia', 'AM', 'Asia'),
('Azerbaijan', 'AZ', 'Asia'),
('Bahrain', 'BH', 'Asia'),
('Bangladesh', 'BD', 'Asia'),
('Bhutan', 'BT', 'Asia'),
('Brunei', 'BN', 'Asia'),
('Cambodia', 'KH', 'Asia'),
('China', 'CN', 'Asia'),
('Cyprus', 'CY', 'Asia'),
('Georgia', 'GE', 'Asia'),
('India', 'IN', 'Asia'),
('Indonesia', 'ID', 'Asia'),
('Iran', 'IR', 'Asia'),
('Iraq', 'IQ', 'Asia'),
('Israel', 'IL', 'Asia'),
('Japan', 'JP', 'Asia'),
('Jordan', 'JO', 'Asia'),
('Kazakhstan', 'KZ', 'Asia'),
('Kuwait', 'KW', 'Asia'),
('Kyrgyzstan', 'KG', 'Asia'),
('Laos', 'LA', 'Asia'),
('Lebanon', 'LB', 'Asia'),
('Malaysia', 'MY', 'Asia'),
('Maldives', 'MV', 'Asia'),
('Mongolia', 'MN', 'Asia'),
('Myanmar', 'MM', 'Asia'),
('Nepal', 'NP', 'Asia'),
('North Korea', 'KP', 'Asia'),
('Oman', 'OM', 'Asia'),
('Pakistan', 'PK', 'Asia'),
('Palestine', 'PS', 'Asia'),
('Philippines', 'PH', 'Asia'),
('Qatar', 'QA', 'Asia'),
('Saudi Arabia', 'SA', 'Asia'),
('Singapore', 'SG', 'Asia'),
('South Korea', 'KR', 'Asia'),
('Sri Lanka', 'LK', 'Asia'),
('Syria', 'SY', 'Asia'),
('Taiwan', 'TW', 'Asia'),
('Tajikistan', 'TJ', 'Asia'),
('Thailand', 'TH', 'Asia'),
('Timor-Leste', 'TL', 'Asia'),
('Turkey', 'TR', 'Asia'),
('Turkmenistan', 'TM', 'Asia'),
('United Arab Emirates', 'AE', 'Asia'),
('Uzbekistan', 'UZ', 'Asia'),
('Vietnam', 'VN', 'Asia'),
('Yemen', 'YE', 'Asia'),

-- Europe
('Albania', 'AL', 'Europe'),
('Andorra', 'AD', 'Europe'),
('Austria', 'AT', 'Europe'),
('Belarus', 'BY', 'Europe'),
('Belgium', 'BE', 'Europe'),
('Bosnia and Herzegovina', 'BA', 'Europe'),
('Bulgaria', 'BG', 'Europe'),
('Croatia', 'HR', 'Europe'),
('Czech Republic', 'CZ', 'Europe'),
('Denmark', 'DK', 'Europe'),
('Estonia', 'EE', 'Europe'),
('Finland', 'FI', 'Europe'),
('France', 'FR', 'Europe'),
('Germany', 'DE', 'Europe'),
('Greece', 'GR', 'Europe'),
('Hungary', 'HU', 'Europe'),
('Iceland', 'IS', 'Europe'),
('Ireland', 'IE', 'Europe'),
('Italy', 'IT', 'Europe'),
('Latvia', 'LV', 'Europe'),
('Liechtenstein', 'LI', 'Europe'),
('Lithuania', 'LT', 'Europe'),
('Luxembourg', 'LU', 'Europe'),
('Malta', 'MT', 'Europe'),
('Moldova', 'MD', 'Europe'),
('Monaco', 'MC', 'Europe'),
('Montenegro', 'ME', 'Europe'),
('Netherlands', 'NL', 'Europe'),
('North Macedonia', 'MK', 'Europe'),
('Norway', 'NO', 'Europe'),
('Poland', 'PL', 'Europe'),
('Portugal', 'PT', 'Europe'),
('Romania', 'RO', 'Europe'),
('Russia', 'RU', 'Europe'),
('San Marino', 'SM', 'Europe'),
('Serbia', 'RS', 'Europe'),
('Slovakia', 'SK', 'Europe'),
('Slovenia', 'SI', 'Europe'),
('Spain', 'ES', 'Europe'),
('Sweden', 'SE', 'Europe'),
('Switzerland', 'CH', 'Europe'),
('Ukraine', 'UA', 'Europe'),
('United Kingdom', 'GB', 'Europe'),
('Vatican City', 'VA', 'Europe'),

-- North America
('Antigua and Barbuda', 'AG', 'North America'),
('Bahamas', 'BS', 'North America'),
('Barbados', 'BB', 'North America'),
('Belize', 'BZ', 'North America'),
('Canada', 'CA', 'North America'),
('Costa Rica', 'CR', 'North America'),
('Cuba', 'CU', 'North America'),
('Dominica', 'DM', 'North America'),
('Dominican Republic', 'DO', 'North America'),
('El Salvador', 'SV', 'North America'),
('Grenada', 'GD', 'North America'),
('Guatemala', 'GT', 'North America'),
('Haiti', 'HT', 'North America'),
('Honduras', 'HN', 'North America'),
('Jamaica', 'JM', 'North America'),
('Mexico', 'MX', 'North America'),
('Nicaragua', 'NI', 'North America'),
('Panama', 'PA', 'North America'),
('Saint Kitts and Nevis', 'KN', 'North America'),
('Saint Lucia', 'LC', 'North America'),
('Saint Vincent and the Grenadines', 'VC', 'North America'),
('Trinidad and Tobago', 'TT', 'North America'),
('United States', 'US', 'North America'),

-- South America
('Argentina', 'AR', 'South America'),
('Bolivia', 'BO', 'South America'),
('Brazil', 'BR', 'South America'),
('Chile', 'CL', 'South America'),
('Colombia', 'CO', 'South America'),
('Ecuador', 'EC', 'South America'),
('Guyana', 'GY', 'South America'),
('Paraguay', 'PY', 'South America'),
('Peru', 'PE', 'South America'),
('Suriname', 'SR', 'South America'),
('Uruguay', 'UY', 'South America'),
('Venezuela', 'VE', 'South America'),

-- Oceania
('Australia', 'AU', 'Oceania'),
('Fiji', 'FJ', 'Oceania'),
('Kiribati', 'KI', 'Oceania'),
('Marshall Islands', 'MH', 'Oceania'),
('Micronesia', 'FM', 'Oceania'),
('Nauru', 'NR', 'Oceania'),
('New Zealand', 'NZ', 'Oceania'),
('Palau', 'PW', 'Oceania'),
('Papua New Guinea', 'PG', 'Oceania'),
('Samoa', 'WS', 'Oceania'),
('Solomon Islands', 'SB', 'Oceania'),
('Tonga', 'TO', 'Oceania'),
('Tuvalu', 'TV', 'Oceania'),
('Vanuatu', 'VU', 'Oceania')

ON CONFLICT (name) DO NOTHING;
